-- MySQL Script generated by MySQL Workbench
-- Fri Mar  7 18:14:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuarios` (
  `ID_tipo_usuarios` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_tipo_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `ID_usuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `tipo_usuarios_ID_tipo_usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_usuarios`),
  CONSTRAINT `fk_Usuarios_tipo_usuarios`
    FOREIGN KEY (`tipo_usuarios_ID_tipo_usuarios`)
    REFERENCES `mydb`.`tipo_usuarios` (`ID_tipo_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuarios_tipo_usuarios_idx` ON `mydb`.`Usuarios` (`tipo_usuarios_ID_tipo_usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pacientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pacientes` (
  `ID_pacientes` INT NOT NULL,
  `Usuarios_ID_usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_pacientes`),
  CONSTRAINT `fk_Pacientes_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`ID_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pacientes_Usuarios1_idx` ON `mydb`.`Pacientes` (`Usuarios_ID_usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `ID_medicos` INT NOT NULL,
  `Usuarios_ID_usuarios` INT NOT NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_medicos`),
  CONSTRAINT `fk_medicos_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`ID_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_medicos_Usuarios1_idx` ON `mydb`.`medicos` (`Usuarios_ID_usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Consultas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Consultas` (
  `ID_consultas` INT NOT NULL,
  `Pacientes_ID_pacientes1` INT NOT NULL,
  `medicos_ID_medicos` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` DATETIME NULL,
  `Motivo` VARCHAR(45) NULL,
  `Diagnostico` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_consultas`),
  CONSTRAINT `fk_Consultas_Pacientes1`
    FOREIGN KEY (`Pacientes_ID_pacientes1`)
    REFERENCES `mydb`.`Pacientes` (`ID_pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_medicos1`
    FOREIGN KEY (`medicos_ID_medicos`)
    REFERENCES `mydb`.`medicos` (`ID_medicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Consultas_Pacientes1_idx` ON `mydb`.`Consultas` (`Pacientes_ID_pacientes1` ASC) VISIBLE;

CREATE INDEX `fk_Consultas_medicos1_idx` ON `mydb`.`Consultas` (`medicos_ID_medicos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tratamientos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tratamientos` (
  `ID_tratamientos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_tratamientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tratamientos_has_Consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tratamientos_has_Consultas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tratamientos_has_Consultas` (
  `Tratamientos_ID_tratamientos` INT NOT NULL,
  `Consultas_ID_consultas` INT NOT NULL,
  PRIMARY KEY (`Tratamientos_ID_tratamientos`, `Consultas_ID_consultas`),
  CONSTRAINT `fk_Tratamientos_has_Consultas_Tratamientos1`
    FOREIGN KEY (`Tratamientos_ID_tratamientos`)
    REFERENCES `mydb`.`Tratamientos` (`ID_tratamientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tratamientos_has_Consultas_Consultas1`
    FOREIGN KEY (`Consultas_ID_consultas`)
    REFERENCES `mydb`.`Consultas` (`ID_consultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tratamientos_has_Consultas_Consultas1_idx` ON `mydb`.`Tratamientos_has_Consultas` (`Consultas_ID_consultas` ASC) VISIBLE;

CREATE INDEX `fk_Tratamientos_has_Consultas_Tratamientos1_idx` ON `mydb`.`Tratamientos_has_Consultas` (`Tratamientos_ID_tratamientos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`citas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `ID_citas` INT NOT NULL,
  `medicos_ID_medicos` INT NOT NULL,
  `Pacientes_ID_pacientes` INT NOT NULL,
  `fecha_solicitud` DATE NULL,
  `estado_solicitud` INT NULL,
  PRIMARY KEY (`ID_citas`),
  CONSTRAINT `fk_citas_medicos1`
    FOREIGN KEY (`medicos_ID_medicos`)
    REFERENCES `mydb`.`medicos` (`ID_medicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_Pacientes1`
    FOREIGN KEY (`Pacientes_ID_pacientes`)
    REFERENCES `mydb`.`Pacientes` (`ID_pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_citas_medicos1_idx` ON `mydb`.`citas` (`medicos_ID_medicos` ASC) VISIBLE;

CREATE INDEX `fk_citas_Pacientes1_idx` ON `mydb`.`citas` (`Pacientes_ID_pacientes` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
