-- MySQL Script generated by MySQL Workbench
-- Mon Mar 10 14:51:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `ID_personas` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `edad` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID_personas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `ID_usuarios` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `personas_ID_personas` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID_usuarios`),
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`personas_ID_personas`)
    REFERENCES `mydb`.`personas` (`ID_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarios_personas1_idx` ON `mydb`.`usuarios` (`personas_ID_personas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuarios` (
  `ID_tipo_usuarios` INT NOT NULL,
  `nombre_tipo_usuario` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarios_ID_usuarios` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID_tipo_usuarios`),
  CONSTRAINT `fk_tipo_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_ID_usuarios`)
    REFERENCES `mydb`.`usuarios` (`ID_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipo_usuarios_usuarios1_idx` ON `mydb`.`tipo_usuarios` (`usuarios_ID_usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Viajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Viajes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Viajes` (
  `ID_viajes` INT NOT NULL,
  `Destino` VARCHAR(45) NULL,
  `Origen` VARCHAR(45) NULL,
  `numero_vuelo` INT NULL,
  `asientos` INT NULL,
  `usuarios_ID_usuarios` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID_viajes`),
  CONSTRAINT `fk_Viajes_usuarios1`
    FOREIGN KEY (`usuarios_ID_usuarios`)
    REFERENCES `mydb`.`usuarios` (`ID_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Viajes_usuarios1_idx` ON `mydb`.`Viajes` (`usuarios_ID_usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_viajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registro_viajes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registro_viajes` (
  `ID_Registro_viajes` INT NOT NULL,
  `numero_viajes` INT NULL,
  `agencia` VARCHAR(45) NULL,
  `llegada` VARCHAR(45) NULL,
  `salida` VARCHAR(45) NULL,
  `Viajes_ID_viajes` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Registro_viajes`),
  CONSTRAINT `fk_Registro_viajes_Viajes`
    FOREIGN KEY (`Viajes_ID_viajes`)
    REFERENCES `mydb`.`Viajes` (`ID_viajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Registro_viajes_Viajes_idx` ON `mydb`.`Registro_viajes` (`Viajes_ID_viajes` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
